version: '3.9'
services:
  app1:
    build: ./app1
    ports:
      - 5001:3000
  app2:
    build: ./app2
    ports:
      - 5002:5000
  nginx:
    build: ./nginx
    ports:
      - 8080:80
    depends_on:
      - app1
      - app2
    restart: always
